# Generated by Django 6.0.2 on 2026-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Drama', max_length=80),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Malayalam', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
